version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: faktulove_postgres
    environment:
      POSTGRES_DB: faktulove_db
      POSTGRES_USER: faktulove_user
      POSTGRES_PASSWORD: faktulove_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U faktulove_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: faktulove_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    container_name: faktulove_celery_worker
    command: celery -A faktury_projekt worker -l info -Q ocr,cleanup
    environment:
      - DJANGO_SETTINGS_MODULE=faktury_projekt.settings
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://faktulove_user:faktulove_password@postgres:5432/faktulove_db
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: faktulove_celery_beat
    command: celery -A faktury_projekt beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=faktury_projekt.settings
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://faktulove_user:faktulove_password@postgres:5432/faktulove_db
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  flower:
    build: .
    container_name: faktulove_flower
    command: celery -A faktury_projekt flower
    environment:
      - DJANGO_SETTINGS_MODULE=faktury_projekt.settings
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: