# Generated by Django 5.1.6 on 2025-03-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='status',
            field=models.CharField(choices=[('wystawiona', 'Wystawiona'), ('oplacona', 'Opłacona'), ('cz_oplacona', 'Częściowo opłacona'), ('anulowana', 'Anulowana')], default='wystawiona', max_length=20),
        ),
    ]
