# Generated by Django 5.1.6 on 2025-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0002_alter_faktura_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrahent',
            name='is_own_company',
            field=models.BooleanField(default=False),
        ),
    ]
