# Generated by Django 5.1.6 on 2025-03-05 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0003_kontrahent_is_own_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrahent',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='kontrahent',
            constraint=models.UniqueConstraint(fields=('firma', 'nip'), name='unique_nip_per_firma'),
        ),
    ]
