# Generated by Django 5.1.6 on 2025-03-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0004_alter_kontrahent_nip_kontrahent_unique_nip_per_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturaCykliczna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cykl', models.CharField(choices=[('D', 'Dzienny'), ('W', 'Tygodniowy'), ('M', 'Miesięczny'), ('K', 'Kwartalny'), ('R', 'Roczny')], default='M', max_length=1)),
                ('data_poczatkowa', models.DateField()),
                ('data_koncowa', models.DateField(blank=True, null=True)),
                ('nastepna_generacja', models.DateField()),
                ('liczba_cykli', models.PositiveIntegerField(default=0)),
                ('aktywna', models.BooleanField(default=True)),
                ('oryginalna_faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faktury.faktura')),
            ],
        ),
    ]
