# Generated by Django 5.1.6 on 2025-03-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0005_fakturacykliczna'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstwo',
            name='data_rozpoczecia',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AddField(
            model_name='partnerstwo',
            name='data_zakonczenia',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AddField(
            model_name='partnerstwo',
            name='opis',
            field=models.TextField(blank=True, null=True, verbose_name='Opis partnerstwa'),
        ),
        migrations.AddField(
            model_name='partnerstwo',
            name='typ_partnerstwa',
            field=models.CharField(choices=[('dostawca', 'Dostawca'), ('odbiorca', 'Odbiorca'), ('wspolpraca', 'Współpraca'), ('inne', 'Inne')], default='wspolpraca', max_length=20, verbose_name='Typ partnerstwa'),
        ),
    ]
