# Generated by Django 5.1.6 on 2025-03-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0006_partnerstwo_data_rozpoczecia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='numer',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
