# Generated by Django 5.1.6 on 2025-03-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0007_alter_faktura_numer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='numer',
            field=models.CharField(max_length=50),
        ),
    ]
