# Generated by Django 5.1.6 on 2025-03-11 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0008_alter_faktura_numer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='data_realizacji',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faktura',
            name='dokument_podstawowy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faktury.faktura', verbose_name='Dokument podstawowy'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='kasa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer kasy'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='metoda_platnosci',
            field=models.CharField(blank=True, choices=[('gotowka', 'Gotówka'), ('przelew', 'Przelew'), ('karta', 'Karta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='typ_dokumentu',
            field=models.CharField(choices=[('FV', 'Faktura VAT'), ('FP', 'Faktura Proforma'), ('KOR', 'Korekta Faktury'), ('RC', 'Rachunek'), ('PAR', 'Paragon'), ('KP', 'KP - Dowód Wpłaty'), ('RB', 'Rachunek Bankowy')], default='FV', max_length=3),
        ),
    ]
