# Generated by Django 5.1.6 on 2025-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0009_faktura_data_realizacji_faktura_dokument_podstawowy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='numer_konta_bankowego',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Numer konta'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='tytul_przelewu',
            field=models.TextField(blank=True, null=True, verbose_name='Tytuł przelewu'),
        ),
    ]
