# Generated by Django 5.1.6 on 2025-03-12 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0010_faktura_numer_konta_bankowego_faktura_tytul_przelewu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to=settings.AUTH_USER_MODEL),
        ),
    ]
