# Generated by Django 5.1.6 on 2025-03-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0011_alter_firma_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='kp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powiazana_faktura', to='faktury.faktura'),
        ),
    ]
