# Generated by Django 5.1.6 on 2025-03-17 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0013_rename_message_notification_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiadomosc',
            options={'ordering': ['-data_wyslania'], 'verbose_name_plural': 'Wiadomości'},
        ),
        migrations.RenameField(
            model_name='wiadomosc',
            old_name='odczytana',
            new_name='przeczytana',
        ),
        migrations.RemoveField(
            model_name='wiadomosc',
            name='zespol',
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='partnerstwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faktury.partnerstwo'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='typ_wiadomosci',
            field=models.CharField(choices=[('partner', 'Od partnera'), ('system', 'Systemowa')], default='partner', max_length=10),
        ),
        migrations.AlterField(
            model_name='wiadomosc',
            name='nadawca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wyslane_wiadomosci', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wiadomosc',
            name='odbiorca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='odebrane_wiadomosci', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
