# Generated by Django 5.1.6 on 2025-03-17 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0014_alter_wiadomosc_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiadomosc',
            name='nadawca',
        ),
        migrations.RemoveField(
            model_name='wiadomosc',
            name='odbiorca',
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='nadawca_czlonek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wyslane_wiadomosci_zespol', to='faktury.czlonekzespolu'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='nadawca_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wyslane_wiadomosci', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='odbiorca_czlonek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odebrane_wiadomosci_zespol', to='faktury.czlonekzespolu'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='odbiorca_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odebrane_wiadomosci', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='faktury.wiadomosc'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='zespol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiadomosci', to='faktury.zespol'),
        ),
        migrations.AlterField(
            model_name='wiadomosc',
            name='typ_wiadomosci',
            field=models.CharField(choices=[('partner', 'Od partnera'), ('system', 'Systemowa'), ('zespol', 'Wiadomość zespołowa')], default='partner', max_length=10),
        ),
    ]
