# Generated by Django 3.2.25 on 2025-08-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faktury', '0015_remove_wiadomosc_nadawca_remove_wiadomosc_odbiorca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='czlonekzespolu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='sposob_platnosci',
            field=models.CharField(choices=[('przelew', 'Przelew'), ('gotowka', 'Gotówka')], default='przelew', max_length=20),
        ),
    ]
