# Generated by Django 4.2.23 on 2025-08-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faktury', '0017_auto_20250822_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faktura',
            options={'ordering': ['-data_wystawienia']},
        ),
        migrations.AlterModelOptions(
            name='fakturacykliczna',
            options={'ordering': ['-data_utworzenia'], 'verbose_name': 'Faktura cykliczna', 'verbose_name_plural': 'Faktury cykliczne'},
        ),
        migrations.RemoveField(
            model_name='wiadomosc',
            name='parent',
        ),
        migrations.AddField(
            model_name='faktura',
            name='auto_ksiegowana',
            field=models.BooleanField(default=False, verbose_name='Auto-księgowana'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='faktura_zrodlowa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktury_pochodne', to='faktury.faktura', verbose_name='Faktura źródłowa'),
        ),
        migrations.AddField(
            model_name='fakturacykliczna',
            name='data_utworzenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakturacykliczna',
            name='dni_przed_generacja',
            field=models.PositiveIntegerField(default=3, verbose_name='Dni przed generacją do powiadomienia'),
        ),
        migrations.AddField(
            model_name='fakturacykliczna',
            name='maksymalna_liczba_cykli',
            field=models.PositiveIntegerField(blank=True, help_text='Maksymalna liczba faktur do wygenerowania', null=True),
        ),
        migrations.AddField(
            model_name='fakturacykliczna',
            name='ostatnia_generacja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fakturacykliczna',
            name='powiadom_o_generacji',
            field=models.BooleanField(default=True, verbose_name='Powiadamiaj o generacji'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utworzone_wiadomosci', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='priorytet',
            field=models.CharField(choices=[('niski', 'Niski'), ('normalny', 'Normalny'), ('wysoki', 'Wysoki')], default='normalny', max_length=10),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='wiadomosc_nadrzedna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='faktury.wiadomosc', verbose_name='Wiadomość nadrzędna'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='zalaczniki',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='fakturacykliczna',
            name='cykl',
            field=models.CharField(choices=[('D', 'Dzienny'), ('W', 'Tygodniowy'), ('2W', 'Co 2 tygodnie'), ('M', 'Miesięczny'), ('2M', 'Co 2 miesiące'), ('3M', 'Co 3 miesiące'), ('6M', 'Co 6 miesięcy'), ('R', 'Roczny')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='fakturacykliczna',
            name='data_koncowa',
            field=models.DateField(blank=True, help_text='Pozostaw puste dla nieskończonego cyklu', null=True),
        ),
        migrations.AlterField(
            model_name='fakturacykliczna',
            name='liczba_cykli',
            field=models.PositiveIntegerField(default=0, help_text='Liczba wygenerowanych faktur'),
        ),
        migrations.AlterField(
            model_name='fakturacykliczna',
            name='oryginalna_faktura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cykle', to='faktury.faktura'),
        ),
        migrations.AddIndex(
            model_name='faktura',
            index=models.Index(fields=['user', 'data_wystawienia'], name='faktury_fak_user_id_289410_idx'),
        ),
        migrations.AddIndex(
            model_name='faktura',
            index=models.Index(fields=['user', 'typ_faktury'], name='faktury_fak_user_id_8e44cc_idx'),
        ),
        migrations.AddIndex(
            model_name='faktura',
            index=models.Index(fields=['numer'], name='faktury_fak_numer_663c07_idx'),
        ),
        migrations.AddIndex(
            model_name='faktura',
            index=models.Index(fields=['status'], name='faktury_fak_status_3bd496_idx'),
        ),
        migrations.AddIndex(
            model_name='faktura',
            index=models.Index(fields=['termin_platnosci'], name='faktury_fak_termin__711fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='faktura',
            index=models.Index(fields=['data_sprzedazy'], name='faktury_fak_data_sp_548015_idx'),
        ),
        migrations.AddIndex(
            model_name='faktura',
            index=models.Index(fields=['typ_dokumentu'], name='faktury_fak_typ_dok_f23a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturacykliczna',
            index=models.Index(fields=['aktywna', 'nastepna_generacja'], name='faktury_fak_aktywna_e48906_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturacykliczna',
            index=models.Index(fields=['oryginalna_faktura'], name='faktury_fak_orygina_6fff8c_idx'),
        ),
        migrations.AddIndex(
            model_name='firma',
            index=models.Index(fields=['nip'], name='faktury_fir_nip_32d324_idx'),
        ),
        migrations.AddIndex(
            model_name='firma',
            index=models.Index(fields=['nazwa'], name='faktury_fir_nazwa_5b6949_idx'),
        ),
        migrations.AddIndex(
            model_name='kontrahent',
            index=models.Index(fields=['user', 'nazwa'], name='faktury_kon_user_id_505c80_idx'),
        ),
        migrations.AddIndex(
            model_name='kontrahent',
            index=models.Index(fields=['nip'], name='faktury_kon_nip_f98740_idx'),
        ),
        migrations.AddIndex(
            model_name='kontrahent',
            index=models.Index(fields=['czy_firma'], name='faktury_kon_czy_fir_fd6dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='produkt',
            index=models.Index(fields=['user', 'nazwa'], name='faktury_pro_user_id_8f4719_idx'),
        ),
        migrations.AddIndex(
            model_name='produkt',
            index=models.Index(fields=['vat'], name='faktury_pro_vat_c824de_idx'),
        ),
        migrations.AddIndex(
            model_name='wiadomosc',
            index=models.Index(fields=['odbiorca_user', 'przeczytana'], name='faktury_wia_odbiorc_95988f_idx'),
        ),
        migrations.AddIndex(
            model_name='wiadomosc',
            index=models.Index(fields=['typ_wiadomosci', 'data_wyslania'], name='faktury_wia_typ_wia_82f8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='wiadomosc',
            index=models.Index(fields=['autor', 'data_wyslania'], name='faktury_wia_autor_i_db733f_idx'),
        ),
    ]
