# Generated by Django 4.2.23 on 2025-08-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0002_add_ocr_models'),
        ('faktury', '0018_alter_faktura_options_alter_fakturacykliczna_options_and_more'),
    ]

    operations = [
    ]
