# Generated by Django 4.2.23 on 2025-08-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0020_enhancedfaktura_enhancedpozycjafaktury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='manual_verification_required',
            field=models.BooleanField(default=False, verbose_name='Wymaga weryfikacji manualnej'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Pewność OCR (%)'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='ocr_extracted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data ekstrakcji OCR'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='ocr_processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Czas przetwarzania OCR (s)'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faktury.documentupload', verbose_name='Dokument źródłowy OCR'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='kp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powiazana_faktury', to='faktury.faktura'),
        ),
    ]
