# Generated by Django 4.2.23 on 2025-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0024_fix_ocr_integration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faktura',
            name='faktury_faktura_ocr_confidence_idx',
        ),
        migrations.RemoveIndex(
            model_name='faktura',
            name='faktury_faktura_manual_verification_idx',
        ),
        migrations.RemoveIndex(
            model_name='faktura',
            name='faktury_faktura_user_ocr_confidence_idx',
        ),
        migrations.RemoveIndex(
            model_name='faktura',
            name='faktury_faktura_user_manual_verification_idx',
        ),
        migrations.RemoveIndex(
            model_name='faktura',
            name='faktury_faktura_ocr_extracted_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='faktura',
            name='faktury_faktura_source_document_idx',
        ),
        migrations.RemoveIndex(
            model_name='ocrresult',
            name='faktury_ocrresult_doc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='faktury_ocr_process_4c13b9_idx',
            old_name='faktury_ocrresult_processing_status_idx',
        ),
        migrations.AlterField(
            model_name='faktura',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Pewność OCR (%)'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='ocr_processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Czas przetwarzania OCR (s)'),
        ),
    ]
