# Generated by Django 4.2.23 on 2025-08-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0025_remove_faktura_faktury_faktura_ocr_confidence_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Przesłany'), ('queued', 'W kolejce'), ('processing', 'Przetwarzany'), ('ocr_completed', 'OCR zakończone'), ('integration_processing', 'Tworzenie faktury'), ('completed', 'Zakończony'), ('failed', 'Błąd'), ('manual_review', 'Wymaga przeglądu'), ('cancelled', 'Anulowany')], default='uploaded', max_length=25, verbose_name='Status przetwarzania'),
        ),
    ]
