# Generated by Django 4.2.23 on 2025-08-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0028_ocr_data_migration_preparation'),
    ]

    operations = [
    ]
