# Generated by Django 4.2.23 on 2025-08-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0030_add_vendor_independence_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ocrengine',
            name='faktury_ocrengine_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='ocrengine',
            name='faktury_ocrengine_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrprocessinglog',
            new_name='faktury_ocr_documen_081bd9_idx',
            old_name='faktury_ocrprocessinglog_doc_time_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrprocessinglog',
            new_name='faktury_ocr_process_78d2b0_idx',
            old_name='faktury_ocrprocessinglog_step_time_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrprocessinglog',
            new_name='faktury_ocr_level_49b430_idx',
            old_name='faktury_ocrprocessinglog_level_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrprocessingstep',
            new_name='faktury_ocr_ocr_res_86933d_idx',
            old_name='faktury_ocrprocessingstep_result_order_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrprocessingstep',
            new_name='faktury_ocr_engine__af0020_idx',
            old_name='faktury_ocrprocessingstep_engine_time_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrprocessingstep',
            new_name='faktury_ocr_step_ty_8bde68_idx',
            old_name='faktury_ocrprocessingstep_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='faktury_ocr_vendor__51385c_idx',
            old_name='faktury_ocrresult_vendor_independent_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='faktury_ocr_google__dc6f81_idx',
            old_name='faktury_ocrresult_google_cloud_replaced_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='faktury_ocr_ocr_eng_93700c_idx',
            old_name='faktury_ocrresult_ocr_engine_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='faktury_ocr_cost_pe_1199ee_idx',
            old_name='faktury_ocrresult_cost_per_processing_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='faktury_ocr_vendor__8564cd_idx',
            old_name='faktury_ocrresult_vendor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrvalidation',
            new_name='faktury_ocr_validat_1f54d0_idx',
            old_name='faktury_ocrvalidation_user_time_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrvalidation',
            new_name='faktury_ocr_accurac_b2ca30_idx',
            old_name='faktury_ocrvalidation_rating_idx',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='best_engine_result',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='engine_results',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='engines_used',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='fallback_used',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='pipeline_version',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='preprocessing_applied',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='primary_engine',
        ),
        migrations.AddIndex(
            model_name='ocrengine',
            index=models.Index(fields=['is_active', 'priority'], name='faktury_ocr_is_acti_cd5e85_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrengine',
            index=models.Index(fields=['engine_type'], name='faktury_ocr_engine__7d8dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrprocessingstep',
            index=models.Index(fields=['step_status'], name='faktury_ocr_step_st_cda199_idx'),
        ),
    ]
