# Generated by Django 4.2.23 on 2025-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0031_remove_ocrengine_faktury_ocrengine_type_active_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='best_engine_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Najlepszy wynik silnika'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='engine_results',
            field=models.JSONField(blank=True, default=dict, verbose_name='Wyniki z poszczególnych silników'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='fallback_used',
            field=models.BooleanField(default=False, verbose_name='Użyto mechanizmu fallback'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='pipeline_version',
            field=models.CharField(default='2.0', max_length=20, verbose_name="Wersja pipeline'u"),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='preprocessing_applied',
            field=models.JSONField(blank=True, default=list, verbose_name='Zastosowane przetwarzanie wstępne'),
        ),
    ]
