# Generated by Django 4.2.23 on 2025-08-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0034_add_rollout_monitoring_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enhancedfaktura',
            name='dokument_podstawowy',
        ),
        migrations.RemoveField(
            model_name='enhancedfaktura',
            name='nabywca',
        ),
        migrations.RemoveField(
            model_name='enhancedfaktura',
            name='sprzedawca',
        ),
        migrations.RemoveField(
            model_name='enhancedfaktura',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enhancedpozycjafaktury',
            name='faktura',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.RemoveField(
            model_name='featureusagelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='RolloutEvent',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_timesta_79a065_idx',
            old_name='performance_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_user_id_1e63aa_idx',
            old_name='performance_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_url_6b75f1_idx',
            old_name='performance_url_idx',
        ),
        migrations.DeleteModel(
            name='EnhancedFaktura',
        ),
        migrations.DeleteModel(
            name='EnhancedPozycjaFaktury',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.DeleteModel(
            name='FeatureUsageLog',
        ),
        migrations.DeleteModel(
            name='RequestLog',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
